#pragma once
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------

#include "XamlBindingInfo.g.h"

namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Controls {
                ref class AppBarButton;
                ref class TextBox;
                ref class ComboBox;
                ref class Button;
                ref class ListView;
            }
        }
    }
}

namespace TextProcessing
{
    [::Windows::Foundation::Metadata::WebHostHidden]
    partial ref class MainPage : public ::Windows::UI::Xaml::Controls::Page, 
        public ::Windows::UI::Xaml::Markup::IComponentConnector,
        public ::Windows::UI::Xaml::Markup::IComponentConnector2
    {
    public:
        void InitializeComponent();
        virtual void Connect(int connectionId, ::Platform::Object^ target);
        virtual ::Windows::UI::Xaml::Markup::IComponentConnector^ GetBindingConnector(int connectionId, ::Platform::Object^ target);
    
    private:
        bool _contentLoaded;
        class MainPage_obj13_Bindings;
        class MainPage_obj1_Bindings;
    
        ::XamlBindingInfo::XamlBindings^ Bindings;
        private: ::Windows::UI::Xaml::Controls::AppBarButton^ SaveBtn;
        private: ::Windows::UI::Xaml::Controls::AppBarButton^ OpenBtn;
        private: ::Windows::UI::Xaml::Controls::TextBox^ TitleBox;
        private: ::Windows::UI::Xaml::Controls::ComboBox^ KingdomBox;
        private: ::Windows::UI::Xaml::Controls::ComboBox^ DivisionBox;
        private: ::Windows::UI::Xaml::Controls::ComboBox^ ClassBox;
        private: ::Windows::UI::Xaml::Controls::ComboBox^ OrderBox;
        private: ::Windows::UI::Xaml::Controls::ComboBox^ FamilyBox;
        private: ::Windows::UI::Xaml::Controls::ComboBox^ GenusBox;
        private: ::Windows::UI::Xaml::Controls::Button^ ActionBtn;
        private: ::Windows::UI::Xaml::Controls::ListView^ PlantView;
    };
}

