//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#include "pch.h"
#include "XamlTypeInfo.g.h"

#include "App.xaml.h"
#include "MainPage.xaml.h"
#include "XamlBindingInfo.g.hpp"
#include "App.g.hpp"
#include "MainPage.g.hpp"

template<typename T>
::Platform::Object^ ActivateType()
{
    return ref new T;
}

template<typename TInstance, typename TItem>
void CollectionAdd(::Platform::Object^ instance, ::Platform::Object^ item)
{
    safe_cast<TInstance^>(instance)->Append((TItem)item);
}

template<typename TInstance, typename TKey, typename TItem>
void DictionaryAdd(::Platform::Object^ instance, ::Platform::Object^ key, ::Platform::Object^ item)
{
    safe_cast<TInstance^>(instance)->Insert((TKey)key, (TItem)item);
}

template<typename T>
::Platform::Object^ FromStringConverter(::XamlTypeInfo::InfoProvider::XamlUserType^ userType, ::Platform::String^ input)
{
    return ref new ::Platform::Box<T>((T)userType->CreateEnumUIntFromString(input));
}

template<typename TDeclaringType>
::Platform::Object^ GetReferenceTypeMember_Plants(::Platform::Object^ instance)
{
    return safe_cast<TDeclaringType^>(instance)->Plants;
}

template<typename TDeclaringType>
::Platform::Object^ GetReferenceTypeMember_Genus(::Platform::Object^ instance)
{
    return safe_cast<TDeclaringType^>(instance)->Genus;
}

template<typename TDeclaringType>
::Platform::Object^ GetReferenceTypeMember_Family(::Platform::Object^ instance)
{
    return safe_cast<TDeclaringType^>(instance)->Family;
}

template<typename TDeclaringType>
::Platform::Object^ GetReferenceTypeMember_Order(::Platform::Object^ instance)
{
    return safe_cast<TDeclaringType^>(instance)->Order;
}

template<typename TDeclaringType>
::Platform::Object^ GetReferenceTypeMember_Class(::Platform::Object^ instance)
{
    return safe_cast<TDeclaringType^>(instance)->Class;
}

template<typename TDeclaringType>
::Platform::Object^ GetReferenceTypeMember_Division(::Platform::Object^ instance)
{
    return safe_cast<TDeclaringType^>(instance)->Division;
}

template<typename TDeclaringType>
::Platform::Object^ GetReferenceTypeMember_Kingdom(::Platform::Object^ instance)
{
    return safe_cast<TDeclaringType^>(instance)->Kingdom;
}

template<typename TDeclaringType>
::Platform::Object^ GetReferenceTypeMember_Title(::Platform::Object^ instance)
{
    return safe_cast<TDeclaringType^>(instance)->Title;
}

template<typename TDeclaringType, typename TValue>
void SetReferenceTypeMember_Plants(::Platform::Object^ instance, ::Platform::Object^ value)
{
    safe_cast<TDeclaringType^>(instance)->Plants = safe_cast<TValue^>(value);
}

template<typename TDeclaringType, typename TValue>
void SetReferenceTypeMember_Genus(::Platform::Object^ instance, ::Platform::Object^ value)
{
    safe_cast<TDeclaringType^>(instance)->Genus = safe_cast<TValue^>(value);
}

template<typename TDeclaringType, typename TValue>
void SetReferenceTypeMember_Family(::Platform::Object^ instance, ::Platform::Object^ value)
{
    safe_cast<TDeclaringType^>(instance)->Family = safe_cast<TValue^>(value);
}

template<typename TDeclaringType, typename TValue>
void SetReferenceTypeMember_Order(::Platform::Object^ instance, ::Platform::Object^ value)
{
    safe_cast<TDeclaringType^>(instance)->Order = safe_cast<TValue^>(value);
}

template<typename TDeclaringType, typename TValue>
void SetReferenceTypeMember_Class(::Platform::Object^ instance, ::Platform::Object^ value)
{
    safe_cast<TDeclaringType^>(instance)->Class = safe_cast<TValue^>(value);
}

template<typename TDeclaringType, typename TValue>
void SetReferenceTypeMember_Division(::Platform::Object^ instance, ::Platform::Object^ value)
{
    safe_cast<TDeclaringType^>(instance)->Division = safe_cast<TValue^>(value);
}

template<typename TDeclaringType, typename TValue>
void SetReferenceTypeMember_Kingdom(::Platform::Object^ instance, ::Platform::Object^ value)
{
    safe_cast<TDeclaringType^>(instance)->Kingdom = safe_cast<TValue^>(value);
}

template<typename TDeclaringType, typename TValue>
void SetReferenceTypeMember_Title(::Platform::Object^ instance, ::Platform::Object^ value)
{
    safe_cast<TDeclaringType^>(instance)->Title = safe_cast<TValue^>(value);
}

struct TypeInfo
{
    PCWSTR  typeName;
    PCWSTR contentPropertyName;
    ::Platform::Object^ (*activator)();
    void (*collectionAdd)(::Platform::Object^, ::Platform::Object^);
    void (*dictionaryAdd)(::Platform::Object^, ::Platform::Object^, ::Platform::Object^);
    ::Platform::Object^ (*fromStringConverter)(::XamlTypeInfo::InfoProvider::XamlUserType^, ::Platform::String^);
    int     baseTypeIndex;
    int     firstMemberIndex;
    int     firstEnumValueIndex;
    ::Windows::UI::Xaml::Interop::TypeKind kindofType;
    bool    isLocalType;
    bool    isSystemType;
    bool    isReturnTypeStub;
    bool    isBindable;
};

TypeInfo TypeInfos[] = 
{
    //   0
    L"Object", L"",
    nullptr, nullptr, nullptr, nullptr,
    -1,
    0, 0, ::Windows::UI::Xaml::Interop::TypeKind::Metadata,
    false, true,  false, false,
    //   1
    L"String", L"",
    nullptr, nullptr, nullptr, nullptr,
    -1,
    0, 0, ::Windows::UI::Xaml::Interop::TypeKind::Metadata,
    false, true,  false, false,
    //   2
    L"TextProcessing.Plant", L"",
    nullptr, nullptr, nullptr, nullptr,
    0, // Object
    0, 0, ::Windows::UI::Xaml::Interop::TypeKind::Custom,
    true,  false, false, false,
    //   3
    L"TextProcessing.MainPage", L"",
    &ActivateType<::TextProcessing::MainPage>, nullptr, nullptr, nullptr,
    4, // Windows.UI.Xaml.Controls.Page
    7, 0, ::Windows::UI::Xaml::Interop::TypeKind::Custom,
    true,  false, false, false,
    //   4
    L"Windows.UI.Xaml.Controls.Page", L"",
    nullptr, nullptr, nullptr, nullptr,
    -1,
    14, 0, ::Windows::UI::Xaml::Interop::TypeKind::Metadata,
    false, true,  false, false,
    //   5
    L"Windows.UI.Xaml.Controls.UserControl", L"",
    nullptr, nullptr, nullptr, nullptr,
    -1,
    14, 0, ::Windows::UI::Xaml::Interop::TypeKind::Metadata,
    false, true,  false, false,
    //   6
    L"Windows.Foundation.Collections.IVector`1<String>", L"",
    nullptr, &CollectionAdd<::Windows::Foundation::Collections::IVector<::Platform::String^>, ::Platform::String^>, nullptr, nullptr,
    -1,
    14, 0, ::Windows::UI::Xaml::Interop::TypeKind::Metadata,
    false, false, true,  false,
    //   7
    L"Windows.Foundation.Collections.IVector`1<TextProcessing.Plant>", L"",
    nullptr, &CollectionAdd<::Windows::Foundation::Collections::IVector<::TextProcessing::Plant^>, ::TextProcessing::Plant^>, nullptr, nullptr,
    -1,
    14, 0, ::Windows::UI::Xaml::Interop::TypeKind::Metadata,
    false, false, true,  false,
    //  Last type here is for padding
    L"", L"",
    nullptr, nullptr, nullptr, nullptr,
    -1, 
    14, 0,::Windows::UI::Xaml::Interop::TypeKind::Custom,
    false, false, false, false,
};

UINT TypeInfoLookup[] = { 
      0,   //   0
      0,   //   1
      0,   //   2
      0,   //   3
      0,   //   4
      0,   //   5
      1,   //   6
      2,   //   7
      2,   //   8
      2,   //   9
      2,   //  10
      2,   //  11
      2,   //  12
      2,   //  13
      2,   //  14
      2,   //  15
      2,   //  16
      2,   //  17
      2,   //  18
      2,   //  19
      2,   //  20
      3,   //  21
      3,   //  22
      3,   //  23
      4,   //  24
      4,   //  25
      4,   //  26
      4,   //  27
      4,   //  28
      4,   //  29
      5,   //  30
      5,   //  31
      5,   //  32
      5,   //  33
      5,   //  34
      5,   //  35
      5,   //  36
      6,   //  37
      6,   //  38
      6,   //  39
      6,   //  40
      6,   //  41
      6,   //  42
      6,   //  43
      6,   //  44
      6,   //  45
      6,   //  46
      6,   //  47
      6,   //  48
      7,   //  49
      7,   //  50
      7,   //  51
      7,   //  52
      7,   //  53
      7,   //  54
      7,   //  55
      7,   //  56
      7,   //  57
      7,   //  58
      7,   //  59
      7,   //  60
      7,   //  61
      7,   //  62
      8,   //  63
};

struct MemberInfo 
{
    PCWSTR shortName;
    ::Platform::Object^ (*getter)(::Platform::Object^);
    void (*setter)(::Platform::Object^, ::Platform::Object^);
    int typeIndex;
    int targetTypeIndex;
    bool isReadOnly;
    bool isDependencyProperty;
    bool isAttachable;
};

MemberInfo MemberInfos[] = 
{
    //   0 - TextProcessing.Plant.Genus
    L"Genus",
    &GetReferenceTypeMember_Genus<::TextProcessing::Plant>,
    &SetReferenceTypeMember_Genus<::TextProcessing::Plant, ::Platform::String>,
    1, // String
    -1,
    false, false, false,
    //   1 - TextProcessing.Plant.Family
    L"Family",
    &GetReferenceTypeMember_Family<::TextProcessing::Plant>,
    &SetReferenceTypeMember_Family<::TextProcessing::Plant, ::Platform::String>,
    1, // String
    -1,
    false, false, false,
    //   2 - TextProcessing.Plant.Order
    L"Order",
    &GetReferenceTypeMember_Order<::TextProcessing::Plant>,
    &SetReferenceTypeMember_Order<::TextProcessing::Plant, ::Platform::String>,
    1, // String
    -1,
    false, false, false,
    //   3 - TextProcessing.Plant.Class
    L"Class",
    &GetReferenceTypeMember_Class<::TextProcessing::Plant>,
    &SetReferenceTypeMember_Class<::TextProcessing::Plant, ::Platform::String>,
    1, // String
    -1,
    false, false, false,
    //   4 - TextProcessing.Plant.Division
    L"Division",
    &GetReferenceTypeMember_Division<::TextProcessing::Plant>,
    &SetReferenceTypeMember_Division<::TextProcessing::Plant, ::Platform::String>,
    1, // String
    -1,
    false, false, false,
    //   5 - TextProcessing.Plant.Kingdom
    L"Kingdom",
    &GetReferenceTypeMember_Kingdom<::TextProcessing::Plant>,
    &SetReferenceTypeMember_Kingdom<::TextProcessing::Plant, ::Platform::String>,
    1, // String
    -1,
    false, false, false,
    //   6 - TextProcessing.Plant.Title
    L"Title",
    &GetReferenceTypeMember_Title<::TextProcessing::Plant>,
    &SetReferenceTypeMember_Title<::TextProcessing::Plant, ::Platform::String>,
    1, // String
    -1,
    false, false, false,
    //   7 - TextProcessing.MainPage.Plants
    L"Plants",
    &GetReferenceTypeMember_Plants<::TextProcessing::MainPage>,
    &SetReferenceTypeMember_Plants<::TextProcessing::MainPage, ::Windows::Foundation::Collections::IVector<::TextProcessing::Plant^>>,
    7, // Windows.Foundation.Collections.IVector`1<TextProcessing.Plant>
    -1,
    false, false, false,
    //   8 - TextProcessing.MainPage.Order
    L"Order",
    &GetReferenceTypeMember_Order<::TextProcessing::MainPage>,
    &SetReferenceTypeMember_Order<::TextProcessing::MainPage, ::Windows::Foundation::Collections::IVector<::Platform::String^>>,
    6, // Windows.Foundation.Collections.IVector`1<String>
    -1,
    false, false, false,
    //   9 - TextProcessing.MainPage.Kingdom
    L"Kingdom",
    &GetReferenceTypeMember_Kingdom<::TextProcessing::MainPage>,
    &SetReferenceTypeMember_Kingdom<::TextProcessing::MainPage, ::Windows::Foundation::Collections::IVector<::Platform::String^>>,
    6, // Windows.Foundation.Collections.IVector`1<String>
    -1,
    false, false, false,
    //  10 - TextProcessing.MainPage.Genus
    L"Genus",
    &GetReferenceTypeMember_Genus<::TextProcessing::MainPage>,
    &SetReferenceTypeMember_Genus<::TextProcessing::MainPage, ::Windows::Foundation::Collections::IVector<::Platform::String^>>,
    6, // Windows.Foundation.Collections.IVector`1<String>
    -1,
    false, false, false,
    //  11 - TextProcessing.MainPage.Family
    L"Family",
    &GetReferenceTypeMember_Family<::TextProcessing::MainPage>,
    &SetReferenceTypeMember_Family<::TextProcessing::MainPage, ::Windows::Foundation::Collections::IVector<::Platform::String^>>,
    6, // Windows.Foundation.Collections.IVector`1<String>
    -1,
    false, false, false,
    //  12 - TextProcessing.MainPage.Division
    L"Division",
    &GetReferenceTypeMember_Division<::TextProcessing::MainPage>,
    &SetReferenceTypeMember_Division<::TextProcessing::MainPage, ::Windows::Foundation::Collections::IVector<::Platform::String^>>,
    6, // Windows.Foundation.Collections.IVector`1<String>
    -1,
    false, false, false,
    //  13 - TextProcessing.MainPage.Class
    L"Class",
    &GetReferenceTypeMember_Class<::TextProcessing::MainPage>,
    &SetReferenceTypeMember_Class<::TextProcessing::MainPage, ::Windows::Foundation::Collections::IVector<::Platform::String^>>,
    6, // Windows.Foundation.Collections.IVector`1<String>
    -1,
    false, false, false,
};

PCWSTR GetShortName(PCWSTR longName)
{
    PCWSTR separator = wcsrchr(longName, '.');
    return separator != nullptr ? separator + 1: longName;
}

TypeInfo* GetTypeInfo(::Platform::String^ typeName)
{
    int typeNameLength = typeName->Length();
    if (typeNameLength < _countof(TypeInfoLookup) - 1)
    {
        for (UINT i = TypeInfoLookup[typeNameLength]; i < TypeInfoLookup[typeNameLength+1]; i++)
        {
            if (typeName == ::Platform::StringReference(TypeInfos[i].typeName))
            {
                return &TypeInfos[i];
            }
        }
    }
    return nullptr;
}

MemberInfo* GetMemberInfo(::Platform::String^ longMemberName)
{
    for (int lastDotIndex = longMemberName->Length(); lastDotIndex >= 0; lastDotIndex--)
    {
        if (longMemberName->Data()[lastDotIndex] == '.')
        {
            TypeInfo* pTypeInfo = GetTypeInfo(ref new ::Platform::String(longMemberName->Data(), lastDotIndex));
            TypeInfo* pNextTypeInfo = pTypeInfo + 1;
            if (pTypeInfo)
            {
                PCWSTR shortMemberName = GetShortName(longMemberName->Data());
                for (int i = pTypeInfo->firstMemberIndex; i < pNextTypeInfo->firstMemberIndex; i++)
                {
                    if (wcscmp(shortMemberName, MemberInfos[i].shortName) == 0)
                    {
                        return &MemberInfos[i];
                    }
                }
            }
            break;
        }
    }
    return nullptr;
}

::Platform::Collections::Vector<::Windows::UI::Xaml::Markup::IXamlMetadataProvider^>^ ::XamlTypeInfo::InfoProvider::XamlTypeInfoProvider::OtherProviders::get()
{
    if(_otherProviders == nullptr)
    {
        auto otherProviders = ref new ::Platform::Collections::Vector<::Windows::UI::Xaml::Markup::IXamlMetadataProvider^>();
        _otherProviders = otherProviders;
    }
    return _otherProviders;
}

::Windows::UI::Xaml::Markup::IXamlType^ ::XamlTypeInfo::InfoProvider::XamlTypeInfoProvider::CreateXamlType(::Platform::String^ typeName)
{
    TypeInfo* pTypeInfo = GetTypeInfo(typeName);
    TypeInfo* pNextTypeInfo = pTypeInfo + 1;
    if (pTypeInfo == nullptr || pNextTypeInfo == nullptr)
    {
        return nullptr;
    }
    else if (pTypeInfo->isSystemType)
    {
        return ref new ::XamlTypeInfo::InfoProvider::XamlSystemBaseType(typeName);
    }
    else
    {
        ::XamlTypeInfo::InfoProvider::XamlUserType^ userType = ref new ::XamlTypeInfo::InfoProvider::XamlUserType(
            this, 
            ::Platform::StringReference(pTypeInfo->typeName), 
            this->GetXamlTypeByName(::Platform::StringReference(pTypeInfo->baseTypeIndex >= 0 ? TypeInfos[pTypeInfo->baseTypeIndex].typeName : L"")));
        userType->KindOfType = pTypeInfo->kindofType;
        userType->Activator = pTypeInfo->activator;
        userType->CollectionAdd = pTypeInfo->collectionAdd;
        userType->DictionaryAdd = pTypeInfo->dictionaryAdd;
        userType->FromStringConverter = pTypeInfo->fromStringConverter;
        userType->ContentPropertyName = ::Platform::StringReference(pTypeInfo->contentPropertyName);
        userType->IsLocalType = pTypeInfo->isLocalType;
        userType->IsReturnTypeStub = pTypeInfo->isReturnTypeStub;
        userType->IsBindable = pTypeInfo->isBindable;
        int nextMemberIndex = pTypeInfo->firstMemberIndex;
        for (int i=pTypeInfo->firstMemberIndex; i < pNextTypeInfo->firstMemberIndex; i++)
        {
            userType->AddMemberName(::Platform::StringReference(MemberInfos[i].shortName));
            nextMemberIndex++;
        }
        return userType;
    }
}

::Windows::UI::Xaml::Markup::IXamlMember^ ::XamlTypeInfo::InfoProvider::XamlTypeInfoProvider::CreateXamlMember(::Platform::String^ longMemberName)
{
    ::XamlTypeInfo::InfoProvider::XamlMember^ xamlMember = nullptr;
    MemberInfo* pMemberInfo = GetMemberInfo(longMemberName);
    if (pMemberInfo != nullptr)
    {
        xamlMember = ref new ::XamlTypeInfo::InfoProvider::XamlMember(
            this,
            ::Platform::StringReference(pMemberInfo->shortName),
            ::Platform::StringReference(TypeInfos[pMemberInfo->typeIndex].typeName));
        xamlMember->Getter = pMemberInfo->getter;
        xamlMember->Setter = pMemberInfo->setter;
        xamlMember->TargetTypeName = pMemberInfo->targetTypeIndex >= 0 ? ::Platform::StringReference(TypeInfos[pMemberInfo->targetTypeIndex].typeName) : L"";
        xamlMember->IsReadOnly = pMemberInfo->isReadOnly;
        xamlMember->IsDependencyProperty = pMemberInfo->isDependencyProperty;
        xamlMember->IsAttachable = pMemberInfo->isAttachable;
    }
    return xamlMember;
}

